/**
 * Content-Only JSON Schema
 *
 * This is the contract for all entity JSON files (treatments, conditions, resources).
 * JSON files MUST contain ONLY domain content and structure, never UI/design/SEO.
 *
 * ALLOWED:
 * - Domain content (clinical data, descriptions, sections)
 * - Structural metadata (type, slug, name)
 * - Editorial metadata (review dates, authors)
 * - Minimal SEO overrides (title, description, no_index only)
 *
 * FORBIDDEN:
 * - UI/design tokens (colors, fonts, spacing, icons, animations)
 * - Layout hints (visual_design, ui_hints, collapsible, ux_display)
 * - SEO blobs (keywords, search_intent, schema_org)
 * - Presentation logic (card styles, layouts, progressive disclosure)
 */

/**
 * Base Entity - Common fields for all entity types
 */
export interface BaseEntity {
  // Core identity
  kind: 'treatment' | 'condition' | 'resource';
  slug: string;
  type: string; // medication, therapy, condition subtype, etc.
  name: string;

  // Content
  summary: string;
  description: string;
  patient_summary?: string;

  // Category (for organization)
  category?: string;

  // Sections (domain content structure)
  sections: ContentSection[];

  // Editorial metadata
  editorial?: EditorialMetadata;

  // FAQs (optional)
  faqs?: FAQ[];

  // Minimal SEO overrides (optional)
  seo?: MinimalSEOOverride;
}

/**
 * Treatment Entity
 */
export interface TreatmentEntity extends BaseEntity {
  kind: 'treatment';
  type: 'medication' | 'therapy' | 'interventional' | 'investigational' | 'alternative' | 'supplement';

  // Treatment-specific metadata
  metadata?: TreatmentMetadata;
  clinical_metadata?: ClinicalMetadata;
}

/**
 * Condition Entity
 */
export interface ConditionEntity extends BaseEntity {
  kind: 'condition';

  // Condition-specific metadata
  metadata?: ConditionMetadata;
}

/**
 * Resource Entity
 */
export interface ResourceEntity extends BaseEntity {
  kind: 'resource';

  // Resource-specific metadata
  metadata?: ResourceMetadata;
}

/**
 * Content Section
 *
 * Defines WHAT content exists and its structure, never HOW it looks.
 */
export interface ContentSection {
  // Section identity
  type: string; // indications, efficacy, warnings, dosing, etc.
  heading?: string; // Optional - some sections may not have headings

  // Content (use appropriate field for section type)
  text?: string;
  intro?: string;
  items?: (string | SectionItem)[];
  key_points?: string[];

  // Section-specific data structures
  [key: string]: any; // Allow type-specific fields
}

export interface SectionItem {
  category?: string;
  quotes?: string[];
  note?: string;
  with?: string;
  risk?: string;
  action?: string;
  symptom?: string;
  incidence?: string;
  patient_note?: string;
  [key: string]: any;
}

/**
 * Editorial Metadata
 */
export interface EditorialMetadata {
  reviewBoard?: string;
  medicalReviewerIds?: string[];
  lastReviewed?: string;
  lastUpdated?: string;
  reviewStatement?: string;

  // Optional individual author/reviewer
  author?: {
    name: string;
    credentials?: string;
    bio?: string;
    url?: string;
  };

  medicalReviewer?: {
    name: string;
    credentials?: string;
    bio?: string;
    url?: string;
  };
}

/**
 * FAQ
 */
export interface FAQ {
  q: string;
  a: string;
}

/**
 * Minimal SEO Override
 *
 * Only these fields are allowed for SEO customization.
 * All other SEO is auto-generated by the central SEO engine.
 */
export interface MinimalSEOOverride {
  title?: string; // Override auto-generated title
  description?: string; // Override auto-generated description
  no_index?: boolean; // Prevent indexing
  canonical?: string; // Custom canonical URL (rare)
}

/**
 * Treatment Metadata
 */
export interface TreatmentMetadata {
  // Drug/medication metadata
  drug_classes?: string[];
  brand_names?: string[];
  administration_routes?: string[];
  prescription_status?: string;
  controlled_substance?: string;
  generic_available?: boolean;
  fda_approval_year?: number;
  pharmacologic_category?: string;

  // Dates
  published_date?: string;
  last_updated?: string;

  // Medical review (legacy - prefer editorial.medical_review)
  medical_review?: {
    reviewed: boolean;
    review_date: string;
    reviewer_name: string;
  };
}

/**
 * Clinical Metadata (treatments)
 */
export interface ClinicalMetadata {
  // Indications
  primary_indications?: string[];
  linked_conditions?: LinkedCondition[];

  // Contraindications
  contraindications?: string[];

  // Efficacy
  efficacy_response?: {
    metric: string;
    percentage_value: string;
    comparison_data?: string;
    patient_text?: string;
    citation_tag?: string;
  };

  // Pharmacokinetics
  pharmacokinetics?: {
    absorption?: string;
    bioavailability?: string;
    onset?: string;
    peak_plasma?: string;
    half_life?: string;
    duration_IR?: string;
    duration_XR?: string;
    metabolism?: string;
    excretion?: string;
    protein_binding?: string;
    food_effect?: string;
  };
}

export interface LinkedCondition {
  slug: string;
  relationship: 'primary_treatment' | 'off_label' | 'investigational';
  context?: string;
}

/**
 * Condition Metadata
 */
export interface ConditionMetadata {
  dsm5_code?: string;
  icd10_codes?: string[];
  category?: string;
  prevalence?: string;
  typical_age_onset?: string;
}

/**
 * Resource Metadata
 */
export interface ResourceMetadata {
  resource_type?: string;
  organization?: string;
  url?: string;
  phone?: string;
  availability?: string;
}

/**
 * Type union for all entity types
 */
export type ContentEntity = TreatmentEntity | ConditionEntity | ResourceEntity;

/**
 * Validation: Forbidden fields
 *
 * These fields are NEVER allowed in content-only JSON.
 * CI validation will reject any JSON containing these fields.
 */
export const FORBIDDEN_FIELDS = [
  // Design tokens
  'visual_design',
  'design_tokens',
  'theme',
  'layout',
  'typography',
  'spacing',
  'colors',
  'cards',
  'icons',
  'animations',

  // UI hints (in sections)
  'ui_hints',
  'ux_display',
  'collapsible',
  'visual_priority',
  'card_style',
  'animation',
  'progressive_disclosure',

  // SEO blobs
  'seo_extensions',
  'keywords',
  'search_intent',
  'search_intent_phrases',
  'search_intent_clusters',
  'schema_org',

  // Presentation hints
  'layout_hints',
  'display_options',
  'render_options'
];

/**
 * Type guard: Check if object is a valid content entity
 */
export function isValidContentEntity(obj: any): obj is ContentEntity {
  if (!obj || typeof obj !== 'object') return false;

  // Required fields
  if (!obj.kind || !obj.slug || !obj.type || !obj.name) return false;
  if (!obj.summary || !obj.description) return false;
  if (!Array.isArray(obj.sections)) return false;

  // Forbidden fields check
  for (const field of FORBIDDEN_FIELDS) {
    if (field in obj) return false;

    // Check sections for forbidden fields
    if (Array.isArray(obj.sections)) {
      for (const section of obj.sections) {
        if (section && typeof section === 'object' && field in section) {
          return false;
        }
      }
    }
  }

  return true;
}

/**
 * Validation result
 */
export interface ValidationResult {
  valid: boolean;
  errors: string[];
  warnings: string[];
}

/**
 * Validate content entity against schema
 */
export function validateContentEntity(obj: any, slug?: string): ValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  const prefix = slug ? `[${slug}] ` : '';

  // Required fields
  if (!obj.kind) errors.push(`${prefix}Missing required field: kind`);
  if (!obj.slug) errors.push(`${prefix}Missing required field: slug`);
  if (!obj.type) errors.push(`${prefix}Missing required field: type`);
  if (!obj.name) errors.push(`${prefix}Missing required field: name`);
  if (!obj.summary) errors.push(`${prefix}Missing required field: summary`);
  if (!obj.description) errors.push(`${prefix}Missing required field: description`);
  if (!obj.sections) errors.push(`${prefix}Missing required field: sections`);

  // Validate sections
  if (Array.isArray(obj.sections)) {
    obj.sections.forEach((section: any, index: number) => {
      if (!section.type) {
        errors.push(`${prefix}Section ${index}: Missing required field: type`);
      }
      if (!section.heading) {
        errors.push(`${prefix}Section ${index}: Missing required field: heading`);
      }
    });
  } else if (obj.sections) {
    errors.push(`${prefix}Field 'sections' must be an array`);
  }

  // Forbidden fields check
  for (const field of FORBIDDEN_FIELDS) {
    if (field in obj) {
      errors.push(`${prefix}Forbidden field: ${field} (UI/design/SEO logic must be in central engines)`);
    }

    // Check sections
    if (Array.isArray(obj.sections)) {
      obj.sections.forEach((section: any, index: number) => {
        if (section && typeof section === 'object' && field in section) {
          errors.push(`${prefix}Section ${index}: Forbidden field: ${field}`);
        }
      });
    }
  }

  // Validate SEO overrides (if present)
  if (obj.seo) {
    const allowedSEOFields = ['title', 'description', 'no_index', 'canonical'];
    for (const key of Object.keys(obj.seo)) {
      if (!allowedSEOFields.includes(key)) {
        errors.push(`${prefix}seo.${key} not allowed (only title, description, no_index, canonical)`);
      }
    }
  }

  // Warnings for recommended fields
  if (!obj.editorial) {
    warnings.push(`${prefix}Recommended field missing: editorial (review metadata)`);
  }

  if (!obj.faqs || obj.faqs.length === 0) {
    warnings.push(`${prefix}Recommended field missing: faqs (improves SEO)`);
  }

  return {
    valid: errors.length === 0,
    errors,
    warnings
  };
}
