/**
 * Architect Domain Schemas
 *
 * Re-exports all schemas, types, and helpers for the Architect domain.
 */

// Lifecycle & Capabilities
export {
  LifecycleStageIdZ,
  CapabilityIdZ,
  LIFECYCLE_STAGES,
  CAPABILITY_REGISTRY,
  getCapabilitiesForStage,
  getOrderedStages,
  getAllCapabilitiesOrdered,
  getStageForCapability,
  isValidCapabilityId,
  getCapability,
  TOTAL_CAPABILITY_COUNT,
  type LifecycleStageId,
  type CapabilityId,
  type LifecycleStageDefinition,
  type CapabilityDefinition,
} from "./lifecycle";

// Practice Fingerprint
export {
  PracticeTypeZ,
  PracticeSizeBucketZ,
  ClinicalRoleZ,
  PopulationZ,
  PayerTypeZ,
  PayerMixZ,
  PrescribingLevelZ,
  DeliveryModelZ,
  PriorityZ,
  USStateZ,
  US_STATES,
  PracticeFingerprintZ,
  PRACTICE_TYPE_LABELS,
  PRACTICE_SIZE_LABELS,
  CLINICAL_ROLE_LABELS,
  POPULATION_LABELS,
  PAYER_TYPE_LABELS,
  PRESCRIBING_LEVEL_LABELS,
  DELIVERY_MODEL_LABELS,
  PRIORITY_LABELS,
  getSizeBucketMidpoint,
  hasBuildForMeRequirements,
  hasAuditRequirements,
  hasPrescribers,
  needsEPCS,
  isInsuranceHeavy,
  isCashPayPrimary,
  getEffectiveProviderCount,
  getPracticeSummary,
  createEmptyFingerprint,
  type PracticeType,
  type PracticeSizeBucket,
  type ClinicalRole,
  type Population,
  type PayerType,
  type PayerMix,
  type PrescribingLevel,
  type DeliveryModel,
  type Priority,
  type USState,
  type PracticeFingerprint,
} from "./fingerprint";

// Product Architecture Metadata
export {
  ProvenanceStatusZ,
  CapabilityStrengthZ,
  ProductCapabilityZ,
  IntegrationTypeZ,
  IntegrationDirectionZ,
  ProductIntegrationZ,
  PracticeFitEvidenceZ,
  PricingBasisZ,
  CurrencyZ,
  PricingTierZ,
  StructuredPricingZ,
  CapabilityMapStatusZ,
  ProductArchitectureMetadataZ,
  CAPABILITY_STRENGTH_VALUES,
  CAPABILITY_STRENGTH_LABELS,
  getStrengthValue,
  getCoverageFromStrength,
  isStrongCoverage,
  createEmptyMetadata,
  type ProvenanceStatus,
  type CapabilityStrength,
  type ProductCapability,
  type IntegrationType,
  type IntegrationDirection,
  type ProductIntegration,
  type PracticeFitEvidence,
  type PricingBasis,
  type Currency,
  type PricingTier,
  type StructuredPricing,
  type CapabilityMapStatus,
  type ProductArchitectureMetadata,
  type ProductCapabilityInput,
  type ProductIntegrationInput,
  type PracticeFitEvidenceInput,
  type StructuredPricingInput,
  type ProductArchitectureMetadataInput,
} from "./product-metadata";

// Practice Stack
export {
  ArchitectModeZ,
  SelectedProductZ,
  RelevanceLevelZ,
  RelevanceOverrideZ,
  StackMutationTypeZ,
  StackHistoryEntryZ,
  PracticeStackZ,
  StackPersistenceEnvelopeZ,
  ARCHITECT_MODE_LABELS,
  RELEVANCE_LEVEL_LABELS,
  RELEVANCE_WEIGHTS,
  STACK_SCHEMA_VERSION,
  createEmptyStack,
  hasProduct,
  getSelectedProduct,
  getProductSlugs,
  getRealProducts,
  getRelevanceOverride,
  createHistoryId,
  addHistoryEntry,
  getLastHistoryEntry,
  canUndo,
  createPersistenceEnvelope,
  parsePersistenceEnvelope,
  type ArchitectMode,
  type SelectedProduct,
  type RelevanceLevel,
  type RelevanceOverride,
  type StackMutationType,
  type StackHistoryEntry,
  type PracticeStack,
  type StackPersistenceEnvelope,
} from "./stack";

// Engine Results
export {
  FitDimensionZ,
  FIT_DIMENSION_WEIGHTS,
  FIT_DIMENSION_LABELS,
  COVERAGE_STATUS_LABELS,
  OVERLAP_CLASSIFICATION_LABELS,
  COMPATIBILITY_STATUS_LABELS,
  SHORTLIST_GROUP_LABELS,
  type FitDimension,
  type FitContribution,
  type FitResult,
  type CoverageStatus,
  type CapabilityCoverage,
  type StageCoverage,
  type StackCoverageResult,
  type OverlapClassification,
  type OverlapAssessment,
  type CompatibilityStatus,
  type CompatibilityAssessment,
  type CostEstimate,
  type HealthSubscore,
  type StackHealthResult,
  type ShortlistGroup,
  type ShortlistItem,
  type ShortlistResult,
  type ReplacementPreview,
} from "./results";
