/**
 * PsychTrails Scenario Registry
 * 
 * ENFORCED: Loads compiled scenario artifacts only.
 * No legacy fallback. No ambiguity.
 * 
 * Compiled artifacts are generated by:
 *   npx tsx src/lib/psychTrail/authoring/build.ts --all
 * 
 * Source of truth: src/lib/psychTrail/authoring/scenarios/<scenario-id>/
 * Compiled output: src/lib/psychTrail/scenarios-compiled/<scenario-id>.json
 */

import type { ScenarioV2 } from "./types-v2";

const SCENARIOS_CACHE = new Map<string, ScenarioV2>();

/**
 * Error thrown when a compiled scenario artifact is not found.
 * This indicates the scenario needs to be built from modular source.
 */
export class ScenarioNotFoundError extends Error {
  public readonly scenarioId: string;
  
  constructor(scenarioId: string) {
    super(
      `Compiled scenario not found: "${scenarioId}".\n` +
      `Run: npx tsx src/lib/psychTrail/authoring/build.ts ${scenarioId}`
    );
    this.name = "ScenarioNotFoundError";
    this.scenarioId = scenarioId;
  }
}

/**
 * Load a scenario from its compiled artifact.
 * 
 * @param scenarioId - The scenario ID (e.g., "dining_hall")
 * @returns The compiled ScenarioV2
 * @throws ScenarioNotFoundError if the compiled artifact does not exist
 */
export async function loadScenario(scenarioId: string): Promise<ScenarioV2> {
  if (SCENARIOS_CACHE.has(scenarioId)) {
    return SCENARIOS_CACHE.get(scenarioId)!;
  }

  // Convert scenario_id to scenario-id for file path (snake_case to kebab-case)
  const fileId = scenarioId.replace(/_/g, "-");

  try {
    const scenario = await import(`./scenarios-compiled/${fileId}.json`);
    const parsed: ScenarioV2 = scenario.default || scenario;
    SCENARIOS_CACHE.set(scenarioId, parsed);
    return parsed;
  } catch {
    throw new ScenarioNotFoundError(scenarioId);
  }
}

/**
 * Get a scenario from cache (synchronous).
 * Returns null if not yet loaded.
 */
export function getScenarioSync(scenarioId: string): ScenarioV2 | null {
  return SCENARIOS_CACHE.get(scenarioId) || null;
}

/**
 * Cache a scenario (for testing or pre-loading).
 */
export function cacheScenario(scenario: ScenarioV2): void {
  SCENARIOS_CACHE.set(scenario.id, scenario);
}

/**
 * Clear the scenario cache.
 */
export function clearCache(): void {
  SCENARIOS_CACHE.clear();
}

/**
 * Load multiple scenarios.
 * Fails if any scenario is missing.
 * 
 * @param scenarioIds - Array of scenario IDs to load
 * @returns Map of scenario ID to ScenarioV2
 * @throws Error listing all missing scenarios
 */
export async function loadAllScenarios(scenarioIds: string[]): Promise<Map<string, ScenarioV2>> {
  const results = new Map<string, ScenarioV2>();
  const errors: string[] = [];

  await Promise.all(
    scenarioIds.map(async (id) => {
      try {
        const scenario = await loadScenario(id);
        results.set(id, scenario);
      } catch (err) {
        if (err instanceof ScenarioNotFoundError) {
          errors.push(id);
        } else {
          throw err;
        }
      }
    })
  );

  if (errors.length > 0) {
    throw new Error(
      `Missing compiled scenarios: ${errors.join(", ")}.\n` +
      `Run: npx tsx src/lib/psychTrail/authoring/build.ts --all`
    );
  }

  return results;
}

/**
 * List all available compiled scenario IDs.
 * For use in tooling/admin only.
 */
export function getAvailableScenarioIds(): string[] {
  // This is a static list for now; can be made dynamic if needed
  return ["dining_hall", "depression_morning_bed"];
}
