import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import "./globals.css";
import { QueryProvider } from "@/components/providers/query-provider";
import { MainLayout } from "@/components/layout/main-layout";

const inter = Inter({ subsets: ["latin"] });

// Viewport configuration for Lighthouse SEO 100/100
// Next.js 14+ requires viewport in separate export from metadata
export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
};

export const metadata: Metadata = {
  metadataBase: new URL(
    process.env.NEXT_PUBLIC_SITE_URL || "https://heypsych.com"
  ),
  title: {
    default: "HeyPsych - Practice Hard Moments Before They Happen",
    template: "%s | HeyPsych",
  },
  description:
    "Build real mental health skills through interactive scenarios. Practice anxiety, social situations, and everyday challenges in safe simulations with PsychTrails.",
  keywords:
    "mental health practice, anxiety training, social anxiety, interactive scenarios, mental health skills, PsychTrails, coping strategies",
  authors: [{ name: "HeyPsych Team" }],
  openGraph: {
    title: "HeyPsych - Practice Hard Moments Before They Happen",
    description:
      "Build real mental health skills through interactive scenarios. Practice anxiety and everyday challenges in safe simulations.",
    type: "website",
    locale: "en_US",
    // Images are auto-generated by opengraph-image.tsx (1200x630)
  },
  twitter: {
    card: "summary_large_image",
    title: "HeyPsych - Practice Hard Moments Before They Happen",
    description:
      "Build real mental health skills through interactive scenarios. Practice anxiety and everyday challenges in safe simulations.",
    // Images are auto-generated by opengraph-image.tsx (1200x630)
  },
  // Simplified favicon configuration for consistent Google Search display
  // Using ONLY favicon.ico to prevent Google from choosing between multiple sources
  icons: {
    icon: "/favicon.ico",
    apple: "/apple-touch-icon.png",
    shortcut: "/favicon.ico",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning>
        <QueryProvider>
          <MainLayout>{children}</MainLayout>
        </QueryProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
