/**
 * GENERATED FILE - DO NOT EDIT
 *
 * Produced by scripts/generate-treatment-aliases.ts from data/treatments/.
 * Run `npm run generate:treatment-aliases` to regenerate.
 *
 * Maps alternate treatment slugs (generic ingredient names, brand names,
 * filename-derived slugs) to the canonical slug that actually renders a page.
 * Consumed by middleware to issue 301s before rendering, so the redirect
 * carries a real status code instead of a streamed soft 404.
 */

/** alias slug -> canonical slug */
export const TREATMENT_SLUG_ALIASES: Readonly<Record<string, string>> = {
  "aat": "animal-assisted-therapy",
  "abft": "attachment-based-family-therapy",
  "abft-p": "attachment-based-family-therapy-parenting",
  "abilify": "aripiprazole-abilify",
  "abilify-asimtufii": "aripiprazole-abilify",
  "abilify-maintena": "aripiprazole-abilify",
  "abilify-mycite": "aripiprazole-abilify",
  "acamprosate": "acamprosate-campral",
  "acceptance-and-commitment-therapy": "acceptance-commitment-therapy",
  "acetyl-l-carnitine-various-brands": "carnitine",
  "act": "acceptance-commitment-therapy",
  "act-memantine": "memantine-namenda",
  "act-zopiclone": "zopiclone-imovane",
  "adapin-historical": "doxepin-sinequan",
  "adasuve": "loxapine-adasuve",
  "adderall": "dextroamphetamine-amphetamine-adderall",
  "adderall-xr": "dextroamphetamine-amphetamine-adderall",
  "adlarity": "donepezil-aricept",
  "advanced-research-lithium-orotate": "lithium-orotate",
  "ag-zopiclone": "zopiclone-imovane",
  "agomelatine": "agomelatine-valdoxan",
  "alcar": "acetyl-l-carnitine",
  "alertec": "modafinil-provigil",
  "algatrium": "algae-omega-3",
  "align-with-b-longum-strains": "bifidobacterium-longum",
  "allergy-relief": "diphenhydramine-benadryl",
  "alprazolam": "alprazolam-xanax",
  "alprazolam-intensol": "alprazolam-xanax",
  "alti-moclobemide": "moclobemide-manerix",
  "amb-buspirone-canada": "buspirone-buspar",
  "ambien": "zolpidem-ambien",
  "ambien-cr": "zolpidem-ambien",
  "american-skullcap": "skullcap",
  "amisulpride": "amisulpride-solian",
  "amitriptyline": "amitriptyline-elavil",
  "amitriptyline-chlordiazepoxide": "amitriptyline-chlordiazepoxide-limbitrol",
  "amoxapine": "amoxapine-asendin",
  "amoxapine-generic": "amoxapine-asendin",
  "ampakines": "ampa-modulators",
  "anafranil": "clomipramine-anafranil",
  "antabuse": "disulfiram-antabuse",
  "aplenzin": "bupropion-wellbutrin",
  "apo-atomoxetine": "atomoxetine-strattera",
  "apo-bromazepam": "bromazepam-lexotan",
  "apo-buspirone-canada": "buspirone-buspar",
  "apo-clobazam": "clobazam-onfi",
  "apo-doxepin": "doxepin-sinequan",
  "apo-fluvoxamine": "fluvoxamine-luvox",
  "apo-guanfacine-xr": "guanfacine-intuniv",
  "apo-loxapine": "loxapine-adasuve",
  "apo-memantine": "memantine-namenda",
  "apo-modafinil": "modafinil-provigil",
  "apo-naltrexone": "naltrexone-vivitrol-revia",
  "apo-oxazepam": "oxazepam-serax",
  "apo-oxcarbazepine": "oxcarbazepine-trileptal-oxtellar-xr",
  "apo-prazo": "prazosin-minipress-ptsd-nightmares",
  "apo-trimipramine-canada": "trimipramine",
  "apo-varenicline": "varenicline-chantix",
  "apo-vortioxetine": "vortioxetine-trintellix",
  "apo-zopiclone": "zopiclone-imovane",
  "aptensio-xr": "methylphenidate-ritalin-concerta",
  "aquasol-e": "vitamin-e",
  "arctic-root": "rhodiola",
  "aricept": "donepezil-aricept",
  "aricept-odt": "donepezil-aricept",
  "aricept-rdt": "donepezil-aricept",
  "aripiprazole": "aripiprazole-abilify",
  "aripiprazole-lauroxil": "aripiprazole-lauroxil-aristada",
  "aristada": "aripiprazole-lauroxil-aristada",
  "aristada-initio": "aripiprazole-lauroxil-aristada",
  "armodafinil": "armodafinil-nuvigil",
  "art": "accelerated-resolution-therapy",
  "ascorbic-acid": "vitamin-c",
  "asenapine": "asenapine-saphris",
  "asendin-historical-brand": "amoxapine-asendin",
  "asian-ginseng": "panax-ginseng",
  "at": "autogenic-training",
  "atarax": "hydroxyzine-vistaril-atarax",
  "ativan": "lorazepam-ativan",
  "atomoxetine": "atomoxetine-strattera",
  "auro-atomoxetine": "atomoxetine-strattera",
  "auro-buspirone-canada": "buspirone-buspar",
  "auro-lurasidone": "lurasidone-latuda",
  "auro-modafinil": "modafinil-provigil",
  "auro-rufinamide": "rufinamide-banzel",
  "auro-ziprasidone": "ziprasidone-geodon",
  "auvelity": "dextromethorphan-bupropion-auvelity",
  "azilect": "rasagiline-azilect",
  "b-100-complex": "b-complex",
  "ba": "behavioral-activation",
  "bacognize": "bacopa-monnieri",
  "bacomind": "bacopa-monnieri",
  "baikal-skullcap": "skullcap",
  "banophen": "diphenhydramine-benadryl",
  "banzel": "rufinamide-banzel",
  "barleans-flax-oil": "flax-seed-oil",
  "barleans-organic-epo": "evening-primrose-oil",
  "basis-nr-pterostilbene": "nad-precursors",
  "bcis": "brain-computer-interfaces",
  "bcm-95": "curcumin",
  "bdt": "brief-dynamic-therapy",
  "belbuca": "buprenorphine-subutex",
  "belsomra": "suvorexant-belsomra",
  "benadryl": "diphenhydramine-benadryl",
  "benefiber": "prebiotic-fiber",
  "betaine-hcl-with-pepsin": "betaine-hcl",
  "betaine-hydrochloride": "betaine-hcl",
  "betaxin": "vitamin-b1-thiamine",
  "bio-zopiclone": "zopiclone-imovane",
  "biogaia-gastrus-combination": "lactobacillus-rhamnosus",
  "biotin": "vitamin-b7-biotin",
  "black-currant-seed-oil": "black-currant-oil",
  "borage-seed-oil": "borage-oil",
  "bpt": "behavioral-parent-training",
  "brevital-sodium": "methohexital-brevital-ect",
  "brexanolone": "brexanolone-zulresso",
  "brexpiprazole": "brexpiprazole-rexulti",
  "brisdelle": "paroxetine-paxil",
  "brixadi": "buprenorphine-subutex",
  "bromazepam": "bromazepam-lexotan",
  "bsft": "brief-strategic-family-therapy",
  "bsft-p": "brief-strategic-family-therapy-parenting",
  "bsp": "brainspotting",
  "bucapsol-us": "buspirone-buspar",
  "buprenex": "buprenorphine-subutex",
  "buprenorphine": "buprenorphine-subutex",
  "buprenorphine-naloxone": "buprenorphine-naloxone-suboxone",
  "bupropion": "bupropion-wellbutrin",
  "buspirone": "buspirone-buspar",
  "butrans": "buprenorphine-subutex",
  "c-1000": "vitamin-c",
  "calciferol": "vitamin-d",
  "calcium-pantothenate": "vitamin-b5-pantothenic-acid",
  "calm-aid": "chamomile",
  "calm-balm": "lemon-balm",
  "calm-magnesium": "magnesium",
  "calmaid": "lavender-oral",
  "calmepam": "bromazepam-lexotan",
  "calmpoppy": "california-poppy",
  "caltrate": "calcium",
  "campral": "acamprosate-campral",
  "carbamazepine": "carbamazepine-tegretol",
  "carbatrol": "carbamazepine-tegretol",
  "cariprazine": "cariprazine-vraylar",
  "carlson-labs-fish-oil": "fish-oil",
  "carnitene": "acetyl-l-carnitine",
  "carnitor": "carnitine",
  "catapres": "clonidine-kapvay-catapres",
  "catapres-tts": "clonidine-kapvay-catapres",
  "cbt": "cognitive-behavioral-therapy",
  "cbt-i": "cognitive-behavioral-therapy-insomnia",
  "celexa": "citalopram-celexa",
  "chaga-extract": "chaga-mushroom",
  "chaga-tea": "chaga-mushroom",
  "chamomile-extract": "chamomile",
  "chamomile-tea": "chamomile",
  "chantix": "varenicline-chantix",
  "chantix-continuing-month-pak": "varenicline-chantix",
  "chantix-starting-month-pak": "varenicline-chantix",
  "chinese-date-extract": "jujube",
  "chinese-herbal-medicine": "herbal-chinese-medicine",
  "chinese-skullcap": "skullcap",
  "chloral-hydrate-odan-canada": "chloral-hydrate",
  "chlorpromazine-generic": "chlorpromazine-thorazine",
  "chromax": "chromium",
  "chromium-picolinate": "chromium",
  "cipralex": "escitalopram-lexapro",
  "circadin": "melatonin",
  "citalopram": "citalopram-celexa",
  "citalopram-generic": "citalopram-celexa",
  "clobazam": "clobazam-onfi",
  "clomipramine": "clomipramine-anafranil",
  "clonazepam": "clonazepam-klonopin",
  "clonidine": "clonidine-kapvay-catapres",
  "clopixol": "zuclopenthixol-clopixol",
  "clopixol-acuphase": "zuclopenthixol-clopixol",
  "clopixol-depot": "zuclopenthixol-clopixol",
  "clorazepate": "clorazepate-tranxene",
  "clozapine": "clozapine-clozaril",
  "clozaril": "clozapine-clozaril",
  "co-buspirone-canada": "buspirone-buspar",
  "coenzyme-q10": "coq10",
  "cognitive-behavioral-therapy-e": "cbt-e",
  "cognitive-behavioral-therapy-for-insomnia": "cognitive-behavioral-therapy-insomnia",
  "cognizin": "citicoline",
  "cold-eeze": "zinc",
  "compazine": "prochlorperazine-compazine",
  "compro": "prochlorperazine-compazine",
  "concerta": "methylphenidate-ritalin-concerta",
  "contrave": "contrave-naltrexone-bupropion",
  "cordyceps-cs-4": "cordyceps",
  "cordyceps-militaris-extract": "cordyceps",
  "cotempla-xr-odt": "methylphenidate-ritalin-concerta",
  "cps": "collaborative-problem-solving",
  "cpt": "cognitive-processing-therapy",
  "creapure": "creatine",
  "creatine-monohydrate": "creatine",
  "creon-prescription-pancreatic-enzymes": "digestive-enzymes",
  "culturelle": "lactobacillus-rhamnosus",
  "culturelle-pro-well": "multi-strain-probiotics",
  "culturelle-probiotics": "bifidobacterium-longum",
  "curcuwin": "curcumin",
  "cyanocobalamin": "vitamin-b12-cobalamin",
  "cymbalta": "duloxetine-cymbalta",
  "cyproheptadine": "cyproheptadine-periactin",
  "d-phenylalanine": "phenylalanine",
  "dalmane": "flurazepam-dalmane",
  "daridorexant": "daridorexant-quviviq",
  "daytrana": "methylphenidate-ritalin-concerta",
  "dayvigo": "lemborexant-dayvigo",
  "dbt": "dialectical-behavior-therapy",
  "depacon": "valproate-depakote",
  "desipramine": "desipramine-norpramin",
  "desoxyn": "methamphetamine-desoxyn",
  "desvenlafaxine": "desvenlafaxine-pristiq",
  "desvenlafaxine-multiple-generics": "desvenlafaxine-pristiq",
  "desyrel": "trazodone-desyrel",
  "dexedrine": "dextroamphetamine-dexedrine",
  "dexedrine-spansule": "dextroamphetamine-dexedrine",
  "dexmethylphenidate": "dexmethylphenidate-focalin",
  "dextroamphetamine": "dextroamphetamine-dexedrine",
  "dextroamphetamine-amphetamine": "dextroamphetamine-amphetamine-adderall",
  "dextromethorphan-bupropion": "dextromethorphan-bupropion-auvelity",
  "diacomit": "stiripentol-diacomit",
  "diastat": "diazepam-valium",
  "diastat-acudial": "diazepam-valium",
  "diazepam": "diazepam-valium",
  "diazepam-intensol": "diazepam-valium",
  "diphenhydramine": "diphenhydramine-benadryl",
  "diskets": "methadone",
  "disulfiram": "disulfiram-antabuse",
  "dl-alpha-tocopherol": "vitamin-e",
  "dlpa": "phenylalanine",
  "dmt": "dance-movement-therapy",
  "doctors-best-5-htp": "5-htp",
  "doctors-best-lithium-orotate": "lithium-orotate",
  "doctors-best-magnesium": "magnesium",
  "dolophine": "methadone",
  "dom-oxazepam": "oxazepam-serax",
  "donepezil": "donepezil-aricept",
  "donepezil-multiple-generics": "donepezil-aricept",
  "doral-discontinued": "quazepam",
  "doxepin": "doxepin-sinequan",
  "drisdol-d2": "vitamin-d",
  "drizalma-sprinkle": "duloxetine-cymbalta",
  "droperidol-generic-injection": "droperidol-inapsine",
  "duloxetine": "duloxetine-cymbalta",
  "duraclon": "clonidine-kapvay-catapres",
  "e-400": "vitamin-e",
  "eat-eap-hippotherapy": "equine-assisted-therapy",
  "ebixa": "memantine-namenda",
  "ect": "electroconvulsive-therapy",
  "edluar": "zolpidem-ambien",
  "efamol": "evening-primrose-oil",
  "effexor-xr": "venlafaxine-effexor-xr",
  "eft": "emotionally-focused-therapy",
  "egb-761": "ginkgo-biloba",
  "egcg-extract": "green-tea-extract",
  "elavil-historical-brand": "amitriptyline-elavil",
  "eleuthero": "siberian-ginseng",
  "elysium-basis": "nad-precursors",
  "emsam": "selegiline-emsam-zelapar",
  "energy-drink-formulations": "taurine",
  "enhanced-cognitive-behavioral-therapy-for-eating-disorders": "cbt-e",
  "enzymedica-digest-gold": "digestive-enzymes",
  "epitol": "carbamazepine-tegretol",
  "eprontia": "topiramate-topamax",
  "equanil": "meprobamate-equanil",
  "equetro": "carbamazepine-tegretol",
  "erp": "exposure-response-prevention",
  "erzofri": "paliperidone-invega",
  "eschscholzia-complex-various-brands": "california-poppy",
  "escitalopram": "escitalopram-lexapro",
  "estazolam": "estazolam-prosom",
  "ester-c": "vitamin-c",
  "eszopiclone": "eszopiclone-lunesta",
  "exelon": "rivastigmine-exelon",
  "exposure-and-response-prevention": "exposure-response-prevention",
  "eye-movement-desensitization-and-reprocessing": "emdr",
  "families-and-schools-together": "families-schools-together",
  "family-based-treatment": "family-based-treatment-fbt",
  "fanapt": "iloperidone-fanapt",
  "fanapt-titration-pack-a": "iloperidone-fanapt",
  "fanapt-titration-pack-b": "iloperidone-fanapt",
  "fanapt-titration-pack-c": "iloperidone-fanapt",
  "fast": "families-schools-together",
  "fbt": "family-based-treatment-fbt",
  "ferrous-fumarate": "iron",
  "ferrous-gluconate": "iron",
  "ferrous-sulfate": "iron",
  "fetzima": "levomilnacipran-fetzima",
  "fetzima-titration": "levomilnacipran-fetzima",
  "fft": "functional-family-therapy",
  "fft-parenting": "functional-family-therapy-parenting",
  "fiber-choice": "prebiotic-fiber",
  "fleet-phospho-soda": "phosphorus",
  "fleqsuvy": "baclofen",
  "fluanxol": "flupentixol-flaunxol",
  "fluanxol-depot": "flupentixol-flaunxol",
  "fluoxetine": "fluoxetine-prozac",
  "fluoxetine-olanzapine": "fluoxetine-olanzapine-symbyax",
  "fluoxetine-various-generics": "fluoxetine-prozac",
  "flupentixol": "flupentixol-flaunxol",
  "fluphenazine": "fluphenazine-prolixin",
  "flurazepam": "flurazepam-dalmane",
  "fluvoxamine": "fluvoxamine-luvox",
  "fmt": "fecal-microbiota-transplantation",
  "focalin": "dexmethylphenidate-focalin",
  "focalin-xr": "dexmethylphenidate-focalin",
  "folate": "vitamin-b9-folate",
  "folic-acid": "vitamin-b9-folate",
  "forfivo-xl": "bupropion-wellbutrin",
  "fps": "family-preservation-services",
  "freshcap-lions-mane": "lion-mane-mushroom",
  "ft-nicotine": "nicotine-replacement-therapy-nrt",
  "ft-sleep-aid-doxylamine": "doxylamine",
  "g115-extract": "panax-ginseng",
  "gabapentin": "gabapentin-neurontin",
  "gabarone": "gabapentin-neurontin",
  "gabitril-dsc": "tiagabine-gabitril",
  "gablofen": "baclofen",
  "galantamine": "galantamine-razadyne-er",
  "galantamine-razadyne": "galantamine-razadyne-er",
  "galvanic-skin-response": "biofeedback-galvanic-skin-response",
  "ganoderma-lucidum-capsules": "reishi-mushroom",
  "garden-of-life-raw-probiotics": "multi-strain-probiotics",
  "generic-amitriptyline": "amitriptyline-elavil",
  "generic-bacopa": "bacopa-monnieri",
  "generic-betaine-hcl-supplements": "betaine-hcl",
  "generic-buprenorphine-naloxone": "buprenorphine-naloxone-suboxone",
  "generic-desipramine-us-canada": "desipramine-norpramin",
  "generic-divalproex-sodium": "valproate-divalproex",
  "generic-valproic-acid": "valproate-divalproex",
  "geodon": "ziprasidone-geodon",
  "geri-dryl": "diphenhydramine-benadryl",
  "gg-probiotic": "lactobacillus-rhamnosus",
  "ginkgold": "ginkgo-biloba",
  "ginsana": "ginseng",
  "gla-support": "black-currant-oil",
  "glucophage": "metformin-psychiatry-weight-gain",
  "glucophage-xr": "metformin-psychiatry-weight-gain",
  "glumetza": "metformin-psychiatry-weight-gain",
  "glutapak": "glutamine",
  "glutasolve": "glutamine",
  "glycerophosphocholine": "alpha-gpc",
  "glysom": "glycine",
  "golden-root": "rhodiola",
  "gralise": "gabapentin-neurontin",
  "gtf-chromium": "chromium",
  "guanfacine": "guanfacine-intuniv",
  "habitrol": "nicotine-replacement-therapy-nrt",
  "halcion": "triazolam-halcion",
  "haldol": "haloperidol-haldol",
  "haldol-decanoate": "haloperidol-haldol",
  "haloperidol": "haloperidol-haldol",
  "heart-rate-variability": "heart-rate-variability-training",
  "hemangeol": "propranolol",
  "hetlioz": "tasimelteon-hetlioz",
  "hetlioz-lq": "tasimelteon-hetlioz",
  "hops-extract": "hops",
  "host-defense-lions-mane": "lion-mane-mushroom",
  "hrt": "habit-reversal-training",
  "humulus-supplement": "hops",
  "hydroxocobalamin": "vitamin-b12-cobalamin",
  "hydroxyzine": "hydroxyzine-vistaril-atarax",
  "hydroxyzine-vistaril": "hydroxyzine-vistaril-atarax",
  "hyperforat": "st-johns-wort",
  "iloperidone": "iloperidone-fanapt",
  "imipramine": "imipramine-tofranil",
  "imovane": "zopiclone-imovane",
  "inapsine": "droperidol-inapsine",
  "inderal-la": "propranolol",
  "inderal-xl": "propranolol",
  "inhaled-nitrous-oxide": "nitrous-oxide-therapy",
  "innopran-xl": "propranolol",
  "intuniv": "guanfacine-intuniv",
  "intuniv-xr": "guanfacine-intuniv",
  "invega": "paliperidone-invega",
  "invega-hafyera": "paliperidone-invega",
  "invega-sustenna": "paliperidone-invega",
  "invega-trinza": "paliperidone-invega",
  "ipt": "interpersonal-therapy",
  "isocarboxazid": "isocarboxazid-marplan",
  "jamp-atomoxetine": "atomoxetine-strattera",
  "jamp-buspirone-canada": "buspirone-buspar",
  "jamp-guanfacine-xr": "guanfacine-intuniv",
  "jamp-lurasidone": "lurasidone-latuda",
  "jamp-modafinil": "modafinil-provigil",
  "jamp-oxcarbazepine-dsc": "oxcarbazepine-trileptal-oxtellar-xr",
  "jamp-zopiclone": "zopiclone-imovane",
  "jarrow-nac": "n-acetyl-cysteine",
  "jornay-pm": "methylphenidate-ritalin-concerta",
  "jujube-seed-supplement": "jujube",
  "k-dur": "potassium",
  "k-phos": "phosphorus",
  "k-tab": "potassium",
  "kaneka-q10": "coq10",
  "kapvay": "clonidine-kapvay-catapres",
  "kava-kava": "kava",
  "kavain-extract": "kava",
  "ketalar": "ketamine-ketalar",
  "ketamine": "ketamine-ketalar",
  "kira": "st-johns-wort",
  "klonopin": "clonazepam-klonopin",
  "klor-con": "potassium",
  "kloxxado": "naloxone-narcan",
  "konakion": "vitamin-k",
  "korean-ginseng": "panax-ginseng",
  "korean-red-ginseng": "ginseng",
  "ksm-66-ashwagandha": "ashwagandha",
  "l-glutamine": "glutamine",
  "l-phenylalanine": "phenylalanine",
  "l-tryptophan": "tryptophan",
  "l-tyrosine": "tyrosine",
  "lacidofil": "lactobacillus-helveticus",
  "lamictal": "lamotrigine-lamictal",
  "lamictal-odt": "lamotrigine-lamictal",
  "lamictal-starter": "lamotrigine-lamictal",
  "lamictal-xr": "lamotrigine-lamictal",
  "lamotrigine": "lamotrigine-lamictal",
  "latuda": "lurasidone-latuda",
  "lavela-ws-1265": "lavender-oral",
  "lavender": "lavender-oral",
  "leci-ps": "phosphatidylcholine",
  "lecithin-phosphatidylcholine-rich": "phosphatidylcholine",
  "lectopam": "bromazepam-lexotan",
  "lemborexant": "lemborexant-dayvigo",
  "levomilnacipran": "levomilnacipran-fetzima",
  "lexapro": "escitalopram-lexapro",
  "lexaurin": "bromazepam-lexotan",
  "lexilium": "bromazepam-lexotan",
  "lexomil": "bromazepam-lexotan",
  "lexotan": "bromazepam-lexotan",
  "lfms": "low-field-magnetic-stimulation",
  "li-160": "st-johns-wort",
  "libervant": "diazepam-valium",
  "librium-common-brand-us-canada": "chlordiazepoxide-librium",
  "limbitrol": "amitriptyline-chlordiazepoxide-limbitrol",
  "limbitrol-ds": "amitriptyline-chlordiazepoxide-limbitrol",
  "lingzhi-extract": "reishi-mushroom",
  "lioresal": "baclofen",
  "lisdexamfetamine": "lisdexamfetamine-vyvanse",
  "lithium": "lithium-lithobid",
  "lithobid": "lithium-lithobid",
  "livercare": "milk-thistle",
  "lkm-metta": "loving-kindness-meditation",
  "lofexidine": "lofexidine-lucemyra",
  "longevinex": "resveratrol",
  "lorazepam": "lorazepam-ativan",
  "lorazepam-intensol": "lorazepam-ativan",
  "loreev-xr": "lorazepam-ativan",
  "lovaza": "fish-oil",
  "loxapac": "loxapine-adasuve",
  "loxapine": "loxapine-adasuve",
  "loxapine-loxitane": "loxapine-adasuve",
  "lucemyra": "lofexidine-lucemyra",
  "lumryz": "sodium-oxybate-xyrem-lumryz",
  "lunesta": "eszopiclone-lunesta",
  "lurasidone": "lurasidone-latuda",
  "luvox": "fluvoxamine-luvox",
  "luvox-cr": "fluvoxamine-luvox",
  "lybalvi": "olanzapine-samidorphan-lybalvi",
  "lyrica": "pregabalin-lyrica",
  "lyrica-cr": "pregabalin-lyrica",
  "lysergic-acid-diethylamide": "lsd-therapy",
  "m-tranylcypromine": "tranylcypromine-parnate",
  "m-zopiclone": "zopiclone-imovane",
  "mag-ox": "magnesium",
  "magnolia-extract": "magnolia-bark",
  "manerix": "moclobemide-manerix",
  "mantra": "mantra-therapy",
  "mantra-eating-disorder-therapy": "mantra-therapy",
  "mar-doxepin": "doxepin-sinequan",
  "mar-modafinil": "modafinil-provigil",
  "mar-zopiclone": "zopiclone-imovane",
  "marplan": "isocarboxazid-marplan",
  "masqueliers-opcs": "grape-seed-extract",
  "maudsley-model-of-anorexia-nervosa-treatment-for-adults": "mantra-therapy",
  "mbct": "mindfulness-based-cognitive-therapy",
  "mbsr": "mindfulness-based-stress-reduction",
  "mbt": "mentalization-based-therapy",
  "mdft": "multidimensional-family-therapy",
  "med-bromazepam": "bromazepam-lexotan",
  "meganatural-bp": "grape-seed-extract",
  "megared": "krill-oil",
  "melatonex": "melatonin",
  "melissa": "lemon-balm",
  "melissa-supreme": "lemon-balm",
  "mellaril": "thioridazine-mellaril",
  "memantine": "memantine-namenda",
  "mental-health-applications": "experimental-gene-therapy",
  "mephyton": "vitamin-k",
  "meprobamate": "meprobamate-equanil",
  "meprobamate-miltown": "meprobamate-equanil",
  "meriva": "curcumin",
  "metadate-cd": "methylphenidate-ritalin-concerta",
  "metformin": "metformin-psychiatry-weight-gain",
  "metformin-antipsychotic-weight-gain-glucophage": "metformin-psychiatry-weight-gain",
  "methadone-dolophine": "methadone",
  "methadone-hcl-intensol": "methadone",
  "methadose": "methadone",
  "methadose-sugar-free": "methadone",
  "methamphetamine": "methamphetamine-desoxyn",
  "methohexital": "methohexital-brevital-ect",
  "methohexital-brevital": "methohexital-brevital-ect",
  "methoprazine": "methotrimeprazine-nozinan",
  "methotrimeprazine": "methotrimeprazine-nozinan",
  "methylcobalamin": "vitamin-b12-cobalamin",
  "methylin": "methylphenidate-ritalin-concerta",
  "methylphenidate": "methylphenidate-ritalin-concerta",
  "mfr": "myofascial-release",
  "micro-k": "potassium",
  "midazolam": "midazolam-versed-nayzilam",
  "midazolam-versed": "midazolam-versed-nayzilam",
  "milk-thistle-extract": "milk-thistle",
  "milnacipran": "milnacipran-savella",
  "minami-vegan-dha": "algae-omega-3",
  "minipress": "prazosin-minipress-ptsd-nightmares",
  "mint-buspirone-canada": "buspirone-buspar",
  "mint-memantine": "memantine-namenda",
  "mint-varenicline": "varenicline-chantix",
  "mint-zopiclone": "zopiclone-imovane",
  "mirtazapine": "mirtazapine-remeron",
  "mixed-amphetamine-salts-adderall": "dextroamphetamine-amphetamine-adderall",
  "mixed-salt-oxybate": "oxybate-mixed-salt-xywav",
  "moban": "molindone-moban",
  "moclobemide": "moclobemide-manerix",
  "moclobemide-aurorix": "moclobemide-manerix",
  "modafinil": "modafinil-provigil",
  "mogadon": "nitrazepam-mogadon",
  "molindone": "molindone-moban",
  "mtfc": "multidimensional-treatment-foster-care",
  "multiple-canadian-generic-brands": "citalopram-celexa",
  "multiple-generic-duloxetine-products": "duloxetine-cymbalta",
  "multiple-generic-escitalopram-products": "escitalopram-lexapro",
  "multiple-generics": "carbamazepine-tegretol",
  "mydayis": "dextroamphetamine-amphetamine-adderall",
  "n-acetyl-l-tyrosine-nalt": "tyrosine",
  "nac-by-now-foods": "n-acetyl-cysteine",
  "nadi-shodhana": "alternate-nostril-breathing",
  "nalmefene": "nalmefene-opvee",
  "nalmefene-selincro": "nalmefene-opvee",
  "naloxone": "naloxone-narcan",
  "naltrexone": "naltrexone-vivitrol-revia",
  "naltrexone-bupropion-contrave": "contrave-naltrexone-bupropion",
  "naltrexone-bupropion-er": "contrave-naltrexone-bupropion",
  "namenda": "memantine-namenda",
  "namenda-xr": "memantine-namenda",
  "narcan": "naloxone-narcan",
  "nardil": "phenelzine-nardil",
  "nascobal": "vitamin-b12-cobalamin",
  "natrol-5-htp": "5-htp",
  "natrol-melatonin": "melatonin",
  "natural-calm": "magnesium",
  "nature-made-flaxseed-oil": "flax-seed-oil",
  "naturopathic-medicine": "naturopathy",
  "navane": "thiothixene-navane",
  "nayzilam": "midazolam-versed-nayzilam",
  "nbo": "newborn-behavioral-observations",
  "nefazodone": "nefazodone-serzone",
  "neptune-krill-oil-nko": "krill-oil",
  "net": "narrative-exposure-therapy",
  "neuleptil-canada": "periciazine-neuleptil",
  "neuro-ps": "phosphatidylserine",
  "neurobion": "b-complex",
  "neurocarnitine": "acetyl-l-carnitine",
  "neurontin": "gabapentin-neurontin",
  "nexiclon-xr": "clonidine-kapvay-catapres",
  "niacinamide": "vitamin-b3-niacin",
  "niacor": "vitamin-b3-niacin",
  "niagen-nr": "nad-precursors",
  "niaspan": "vitamin-b3-niacin",
  "nicoderm-cq": "nicotine-replacement-therapy-nrt",
  "nicorette": "nicotine-replacement-therapy-nrt",
  "nicorette-mini": "nicotine-replacement-therapy-nrt",
  "nicotine-replacement": "nicotine-replacement-therapy-nrt",
  "nicotine-replacement-therapy": "nicotine-replacement-therapy-nrt",
  "nicotrol-ns": "nicotine-replacement-therapy-nrt",
  "nitrazepam": "nitrazepam-mogadon",
  "nordic-naturals": "fish-oil",
  "norpramin-us": "desipramine-norpramin",
  "nortriptyline": "nortriptyline-pamelor",
  "novo-doxepin": "doxepin-sinequan",
  "novo-hydroxyzin-dsc": "hydroxyzine-vistaril-atarax",
  "now-5-htp": "5-htp",
  "now-evening-primrose-oil": "evening-primrose-oil",
  "now-flax-seed-oil": "flax-seed-oil",
  "now-gaba": "gaba-supplement",
  "now-super-enzymes": "digestive-enzymes",
  "nozinan": "methotrimeprazine-nozinan",
  "nra-lurasidone": "lurasidone-latuda",
  "nra-varenicline": "varenicline-chantix",
  "nra-zopiclone": "zopiclone-imovane",
  "nuvigil": "armodafinil-nuvigil",
  "olanzapine": "olanzapine-zyprexa",
  "olanzapine-fluoxetine": "olanzapine-fluoxetine-symbyax",
  "olanzapine-pamoate-zyprexa-relprevv": "olanzapine-zyprexa",
  "olanzapine-samidorphan": "olanzapine-samidorphan-lybalvi",
  "oleptro": "trazodone-desyrel",
  "omacor": "fish-oil",
  "omt": "osteopathic-manipulation",
  "ondansetron": "ondansetron-zofran",
  "onfi": "clobazam-onfi",
  "onstryv": "safinamide-xadago",
  "onyda-xr": "clonidine-kapvay-catapres",
  "opipza": "aripiprazole-abilify",
  "opvee": "nalmefene-opvee",
  "orap": "pimozide-orap",
  "oscal": "calcium",
  "osteopathic-manipulative-treatment": "osteopathic-manipulation",
  "ot": "occupational-therapy",
  "ovega-3": "algae-omega-3",
  "oxazepam": "oxazepam-serax",
  "oxcarbazepine": "oxcarbazepine-trileptal-oxtellar-xr",
  "oxcarbazepine-trileptal": "oxcarbazepine-trileptal-oxtellar-xr",
  "oxtellar-xr": "oxcarbazepine-trileptal-oxtellar-xr",
  "oxybate-sodium-lumryz": "sodium-oxybate-xyrem-lumryz",
  "ozempic": "glp1",
  "ozobax": "baclofen",
  "paliperidone": "paliperidone-invega",
  "pamelor": "nortriptyline-pamelor",
  "panax-quinquefolius": "american-ginseng",
  "panthenol-pro-vitamin-b5-topical": "vitamin-b5-pantothenic-acid",
  "pantothenic-acid": "vitamin-b5-pantothenic-acid",
  "parent-led-play-therapy": "filial-therapy",
  "parnate": "tranylcypromine-parnate",
  "paroxetine": "paroxetine-paxil",
  "passiflora-extract": "passionflower",
  "passionflower-tea": "passionflower",
  "paxil": "paroxetine-paxil",
  "paxil-cr": "paroxetine-paxil",
  "pcit": "parent-child-interaction-therapy",
  "pct": "person-centered-therapy",
  "pe": "prolonged-exposure-therapy",
  "periactin": "cyproheptadine-periactin",
  "periciazine": "periciazine-neuleptil",
  "perika": "st-johns-wort",
  "permixon": "saw-palmetto",
  "perphenazine": "perphenazine-trilafon",
  "perphenazine-amitriptyline-triavil": "amitriptyline-perphenazine",
  "perseris": "risperidone-risperdal",
  "pharmagaba": "gaba-supplement",
  "pharmanac": "n-acetyl-cysteine",
  "phenelzine": "phenelzine-nardil",
  "phenergan": "promethazine-phenergan",
  "phenobarbital": "phenobarbital-sezaby",
  "phoschol": "phosphatidylcholine",
  "phospha-250": "phosphorus",
  "phytonadione": "vitamin-k",
  "pimozide": "pimozide-orap",
  "pip": "parent-infant-psychotherapy",
  "pmr": "progressive-muscle-relaxation",
  "pms-atomoxetine": "atomoxetine-strattera",
  "pms-buspirone-canada": "buspirone-buspar",
  "pms-lurasidone": "lurasidone-latuda",
  "pms-memantine": "memantine-namenda",
  "pms-zopiclone": "zopiclone-imovane",
  "pmt": "parent-management-training",
  "pns": "peripheral-nerve-stimulation",
  "prazosin": "prazosin-minipress-ptsd-nightmares",
  "prazosin-minipress": "prazosin-minipress-ptsd-nightmares",
  "prebiotin": "prebiotic-fiber",
  "pregabalin": "pregabalin-lyrica",
  "priligy": "dapoxetine-priligy",
  "pristiq": "desvenlafaxine-pristiq",
  "pro-buspirone-canada": "buspirone-buspar",
  "pro-oxazepam": "oxazepam-serax",
  "pro-zopiclone": "zopiclone-imovane",
  "probiostick": "lactobacillus-helveticus",
  "probuphine": "buprenorphine-subutex",
  "procentra": "dextroamphetamine-dexedrine",
  "prochlorperazine": "prochlorperazine-compazine",
  "prolixin": "fluphenazine-prolixin",
  "promethazine": "promethazine-phenergan",
  "promethegan": "promethazine-phenergan",
  "propranolol-inderal": "propranolol",
  "prosom": "estazolam-prosom",
  "prostamol-uno": "saw-palmetto",
  "protriptyline": "protriptyline-vivactil",
  "provigil": "modafinil-provigil",
  "prozac": "fluoxetine-prozac",
  "psk": "turkey-tail-mushroom",
  "psp": "turkey-tail-mushroom",
  "pure-encapsulations-lithium-orotate": "lithium-orotate",
  "pure-glycine": "glycine",
  "pyridoxal-5-phosphate-p5p": "vitamin-b6-pyridoxine",
  "pyridoxine": "vitamin-b6-pyridoxine",
  "q-sorb-coq10": "coq10",
  "qelbree": "viloxazine-qelbree",
  "quazepam-doral": "quazepam",
  "qudexy-xr": "topiramate-topamax",
  "quercesorb": "quercetin",
  "quercetin-complex": "quercetin",
  "quercetin-phytosome": "quercetin",
  "quetiapine": "quetiapine-seroquel",
  "quillichew-er": "methylphenidate-ritalin-concerta",
  "quillivant-xr": "methylphenidate-ritalin-concerta",
  "quviviq": "daridorexant-quviviq",
  "raldesy": "trazodone",
  "ramelteon": "ramelteon-rozerem",
  "rasagiline": "rasagiline-azilect",
  "razadyne": "galantamine-razadyne-er",
  "razadyne-er": "galantamine-razadyne-er",
  "rdi": "relationship-development-intervention",
  "real-mushrooms-lions-mane": "lion-mane-mushroom",
  "rebt": "rational-emotive-behavior-therapy",
  "redoxon": "vitamin-c",
  "reference-brands-vary-by-region": "aniracetam",
  "reishimax": "reishi-mushroom",
  "relexxii": "methylphenidate-ritalin-concerta",
  "relora-magnolia-phellodendron-blend": "magnolia-bark",
  "remeron": "mirtazapine-remeron",
  "remeron-soltab": "mirtazapine-remeron",
  "restoril": "temazepam-restoril",
  "resvida": "resveratrol",
  "revia": "naltrexone-vivitrol-revia",
  "rextovy": "naloxone-narcan",
  "rexulti": "brexpiprazole-rexulti",
  "rhodaxon": "rhodiola",
  "riboflavin": "vitamin-b2-riboflavin",
  "riomet": "metformin-psychiatry-weight-gain",
  "risperdal": "risperidone-risperdal",
  "risperdal-consta": "risperidone-risperdal",
  "risperidone": "risperidone-risperdal",
  "ritalin": "methylphenidate-ritalin-concerta",
  "ritalin-la": "methylphenidate-ritalin-concerta",
  "riva-atomoxetine": "atomoxetine-strattera",
  "riva-memantine": "memantine-namenda",
  "riva-oxazepam": "oxazepam-serax",
  "riva-zopiclone": "zopiclone-imovane",
  "rivastigmine": "rivastigmine-exelon",
  "rivive": "naloxone-narcan",
  "rivotril": "clonazepam-klonopin",
  "rosavin": "rhodiola",
  "rozerem": "ramelteon-rozerem",
  "rufinamide": "rufinamide-banzel",
  "rybelsus": "glp1",
  "rykindo": "risperidone-risperdal",
  "sabril": "vigabatrin-sabril",
  "safinamide": "safinamide-xadago",
  "sandoz-atomoxetine": "atomoxetine-strattera",
  "sandoz-lurasidone": "lurasidone-latuda",
  "sandoz-memantine": "memantine-namenda",
  "saphris-sublingual": "asenapine-saphris",
  "sarafem": "fluoxetine-prozac",
  "savella": "milnacipran-savella",
  "savella-titration-pack": "milnacipran-savella",
  "saxenda": "glp1",
  "scs": "spinal-cord-stimulation",
  "se": "somatic-experiencing",
  "seasonal-affective-disorder": "seasonal-affective-disorder-lamp",
  "secuado-transdermal-patch": "asenapine-saphris",
  "sedapass": "passionflower",
  "sedonium": "valerian-root",
  "seizalam": "midazolam-versed-nayzilam",
  "selegiline": "selegiline-emsam-zelapar",
  "selegiline-emsam": "selegiline-emsam-zelapar",
  "selenase": "selenium",
  "selenoexcell": "selenium",
  "selenomet": "selenium",
  "sensoril": "ashwagandha",
  "sensorimotor-rhythm-training": "smr-neurofeedback",
  "serax": "oxazepam-serax",
  "serenoa-repens-extract": "saw-palmetto",
  "serinaid": "phosphatidylserine",
  "seroquel": "quetiapine-seroquel",
  "seroquel-xr": "quetiapine-seroquel",
  "sertraline": "sertraline-zoloft",
  "serzone": "nefazodone-serzone",
  "sezaby": "phenobarbital-sezaby",
  "sfbt": "solution-focused-brief-therapy",
  "sfp": "strengthening-families-program",
  "sharp-ps": "phosphatidylserine",
  "siberian-ginseng-extract": "siberian-ginseng",
  "silenor": "doxepin-sinequan",
  "silexan": "lavender-oral",
  "silymarin": "milk-thistle",
  "simply-sleep": "diphenhydramine-benadryl",
  "sinequan": "doxepin-sinequan",
  "slo-niacin": "vitamin-b3-niacin",
  "slow-fe": "iron",
  "sodium-oxybate": "sodium-oxybate-xyrem-lumryz",
  "solian": "amisulpride-solian",
  "somazina": "citicoline",
  "sonata": "zaleplon-sonata",
  "starflower-oil": "borage-oil",
  "stdt": "short-term-dynamic-therapy",
  "stelazine": "trifluoperazine-stelazine",
  "stiripentol": "stiripentol-diacomit",
  "strattera": "atomoxetine-strattera",
  "sublocade": "buprenorphine-subutex",
  "suboxone": "buprenorphine-naloxone-suboxone",
  "subutex": "buprenorphine-subutex",
  "subvenite": "lamotrigine-lamictal",
  "subvenite-starter-kit": "lamotrigine-lamictal",
  "suntheanine": "l-theanine",
  "super-b-complex": "b-complex",
  "superba-krill-oil": "krill-oil",
  "suvorexant": "suvorexant-belsomra",
  "sympazan": "clobazam-onfi",
  "synapsa": "bacopa-monnieri",
  "taro-lurasidone": "lurasidone-latuda",
  "taro-zopiclone": "zopiclone-imovane",
  "tasimelteon": "tasimelteon-hetlioz",
  "taurine-generic": "taurine",
  "tcm": "traditional-chinese-medicine",
  "tdcs": "transcranial-direct-current-stimulation",
  "teavigo": "green-tea-extract",
  "tebonin": "ginkgo-biloba",
  "tegretol": "carbamazepine-tegretol",
  "tegretol-xr": "carbamazepine-tegretol",
  "temazepam": "temazepam-restoril",
  "tenex": "guanfacine-intuniv",
  "testa-omega-3": "algae-omega-3",
  "teva-atomoxetine": "atomoxetine-strattera",
  "teva-bromazepam": "bromazepam-lexotan",
  "teva-buspirone-canada": "buspirone-buspar",
  "teva-chlorpromazine-canada": "chlorpromazine-thorazine",
  "teva-clobazam": "clobazam-onfi",
  "teva-fluvoxamine": "fluvoxamine-luvox",
  "teva-haloperidol-canada": "haloperidol-haldol",
  "teva-modafinil": "modafinil-provigil",
  "teva-prazosin": "prazosin-minipress-ptsd-nightmares",
  "teva-varenicline": "varenicline-chantix",
  "teva-zopiclone": "zopiclone-imovane",
  "tf-cbt": "trauma-focused-cbt",
  "tfft": "trauma-focused-family-therapy",
  "tft": "transference-focused-therapy",
  "tfus": "transcranial-focused-ultrasound",
  "theacalm": "l-theanine",
  "theracurmin": "curcumin",
  "thiamin": "vitamin-b1-thiamine",
  "thioridazine": "thioridazine-mellaril",
  "thiothixene": "thiothixene-navane",
  "thorne-gaba": "gaba-supplement",
  "thrive": "nicotine-replacement-therapy-nrt",
  "thymanax": "agomelatine-valdoxan",
  "tiagabine": "tiagabine-gabitril",
  "tm": "transcendental-meditation",
  "tms": "transcranial-magnetic-stimulation",
  "tofranil": "imipramine-tofranil",
  "tofranil-pm": "imipramine-tofranil",
  "topamax": "topiramate-topamax",
  "topamax-sprinkle": "topiramate-topamax",
  "topiramate": "topiramate-topamax",
  "trans-resveratrol": "resveratrol",
  "tranxene": "clorazepate-tranxene",
  "tranxene-t": "clorazepate-tranxene",
  "tranylcypromine": "tranylcypromine-parnate",
  "trauma-focused-cognitive-behavioral-therapy": "trauma-focused-cbt",
  "triazolam": "triazolam-halcion",
  "trifluoperazine": "trifluoperazine-stelazine",
  "trilafon": "perphenazine-trilafon",
  "trileptal": "oxcarbazepine-trileptal-oxtellar-xr",
  "trimipramine-surmontil": "trimipramine",
  "trintellix": "vortioxetine-trintellix",
  "tris": "triple-reuptake-inhibitors",
  "trokendi-xr": "topiramate-topamax",
  "tru-niagen": "nad-precursors",
  "tryptopure": "tryptophan",
  "tums-calcium-carbonate": "calcium",
  "turkey-tail": "turkey-tail-mushroom",
  "tus": "transcranial-ultrasound",
  "ubiquinol": "coq10",
  "uzedy": "risperidone-risperdal",
  "valdoxan": "agomelatine-valdoxan",
  "valerian": "valerian-root",
  "valeriana": "valerian-root",
  "valium": "diazepam-valium",
  "valtoco": "diazepam-valium",
  "varenicline": "varenicline-chantix",
  "various-generics": "chlordiazepoxide-librium",
  "various-probiotic-blends": "bifidobacterium-breve",
  "vat": "vibroacoustic-therapy",
  "venlafaxine": "venlafaxine-effexor-xr",
  "venlafaxine-effexor": "venlafaxine-effexor-xr",
  "versacloz": "clozapine-clozaril",
  "versed": "midazolam-versed-nayzilam",
  "victoza": "glp1",
  "vig": "video-interaction-guidance",
  "vigabatrin": "vigabatrin-sabril",
  "vigadrone": "vigabatrin-sabril",
  "vigafyde": "vigabatrin-sabril",
  "viibryd": "vilazodone-viibryd",
  "viibryd-starter-pack": "vilazodone-viibryd",
  "vilazodone": "vilazodone-viibryd",
  "viloxazine-er": "viloxazine-qelbree",
  "viloxazine-er-qelbree": "viloxazine-qelbree",
  "vistaril-dsc": "hydroxyzine-vistaril-atarax",
  "vitamin-b1": "vitamin-b1-thiamine",
  "vitamin-b12": "vitamin-b12-cobalamin",
  "vitamin-b2": "vitamin-b2-riboflavin",
  "vitamin-b3": "vitamin-b3-niacin",
  "vitamin-b5": "vitamin-b5-pantothenic-acid",
  "vitamin-b6": "vitamin-b6-pyridoxine",
  "vitamin-b7": "vitamin-b7-biotin",
  "vitamin-b9": "vitamin-b9-folate",
  "vivactil": "protriptyline-vivactil",
  "vivitrol": "naltrexone-vivitrol-revia",
  "vns": "vagus-nerve-stimulation",
  "vortioxetine": "vortioxetine-trintellix",
  "vraylar": "cariprazine-vraylar",
  "vsl-3": "multi-strain-probiotics",
  "vyvanse": "lisdexamfetamine-vyvanse",
  "watch-wait-and-wonder": "watch-wait-wonder",
  "wegovy": "glp1",
  "wellbutrin-sr": "bupropion-wellbutrin",
  "wellbutrin-xl": "bupropion-wellbutrin",
  "withania-somnifera": "ashwagandha",
  "www": "watch-wait-wonder",
  "xadago": "safinamide-xadago",
  "xanax": "alprazolam-xanax",
  "xanax-xr": "alprazolam-xanax",
  "xelstrym": "dextroamphetamine-dexedrine",
  "xylac": "loxapine-adasuve",
  "xyrem": "sodium-oxybate-xyrem-lumryz",
  "xywav": "oxybate-mixed-salt-xywav",
  "yakult-b-breve-strains": "bifidobacterium-breve",
  "yakult-probiotic-blends": "bifidobacterium-longum",
  "yogic-breathwork": "pranayama",
  "zaleplon": "zaleplon-sonata",
  "zazen": "zen-meditation",
  "zelapar": "selegiline-emsam-zelapar",
  "zeldox": "ziprasidone-geodon",
  "zenzedi": "dextroamphetamine-dexedrine",
  "zicam": "zinc",
  "zimhi": "naloxone-narcan",
  "zincate": "zinc",
  "ziprasidone": "ziprasidone-geodon",
  "zofran": "ondansetron-zofran",
  "zofran-odt": "ondansetron-zofran",
  "zoloft": "sertraline-zoloft",
  "zolpidem": "zolpidem-ambien",
  "zolpimist-discontinued-in-us": "zolpidem-ambien",
  "zonegran": "zonisamide-zonegran-zonisade",
  "zonisade": "zonisamide-zonegran-zonisade",
  "zonisamide": "zonisamide-zonegran-zonisade",
  "zonisamide-zonegran": "zonisamide-zonegran-zonisade",
  "zopiclone": "zopiclone-imovane",
  "zubsolv": "buprenorphine-naloxone-suboxone",
  "zuclopenthixol": "zuclopenthixol-clopixol",
  "zulresso": "brexanolone-zulresso",
  "zuplenz-oral-soluble-film-discontinued-in-the-united-states": "ondansetron-zofran",
  "zuranolone": "zuranolone-zurzuvae",
  "zurnai": "nalmefene-opvee",
  "zurzuvae": "zuranolone-zurzuvae",
  "zyban": "bupropion-wellbutrin",
  "zyprexa": "olanzapine-zyprexa",
  "zyprexa-relprevv": "olanzapine-zyprexa",
  "zyprexa-zydis": "olanzapine-zyprexa",
  "zzzquil": "diphenhydramine-benadryl",
};

/** Every slug that resolves to a real treatment page. */
export const CANONICAL_TREATMENT_SLUGS: ReadonlySet<string> = new Set([
  "1-2-3-magic",
  "4-7-8-breathing",
  "5-htp",
  "5-meo-dmt-therapy",
  "acamprosate-campral",
  "accelerated-resolution-therapy",
  "acceptance-commitment-therapy",
  "acetyl-l-carnitine",
  "acupuncture",
  "adventure-therapy",
  "agomelatine-valdoxan",
  "alexander-technique",
  "algae-omega-3",
  "alpha-gpc",
  "alpha-theta-neurofeedback",
  "alprazolam-xanax",
  "alternate-nostril-breathing",
  "american-ginseng",
  "amisulpride-solian",
  "amitriptyline-chlordiazepoxide-limbitrol",
  "amitriptyline-elavil",
  "amitriptyline-perphenazine",
  "amoxapine-asendin",
  "ampa-modulators",
  "animal-assisted-therapy",
  "aniracetam",
  "anos-family-approach",
  "aripiprazole-abilify",
  "aripiprazole-lauroxil-aristada",
  "armodafinil-nuvigil",
  "art-therapy",
  "asenapine-saphris",
  "ashwagandha",
  "atomoxetine-strattera",
  "attachment-based-family-therapy",
  "attachment-based-family-therapy-parenting",
  "auricular-acupuncture",
  "authoritative-parenting-training",
  "autogenic-training",
  "ayahuasca-therapy",
  "ayurveda",
  "ayurvedic-herbs",
  "b-complex",
  "baclofen",
  "bacopa-monnieri",
  "behavioral-activation",
  "behavioral-parent-training",
  "beta-neurofeedback",
  "betaine-hcl",
  "bibliotherapy",
  "bifidobacterium-breve",
  "bifidobacterium-longum",
  "binaural-beats",
  "biofeedback-emg",
  "biofeedback-galvanic-skin-response",
  "biofeedback-thermal",
  "black-currant-oil",
  "blue-light-therapy",
  "body-scan-meditation",
  "borage-oil",
  "bowen-family-systems",
  "box-breathing",
  "brain-computer-interfaces",
  "brainspotting",
  "brazelton-touchpoints",
  "breath-of-fire",
  "brexanolone-zulresso",
  "brexpiprazole-rexulti",
  "brief-dynamic-therapy",
  "brief-strategic-family-therapy",
  "brief-strategic-family-therapy-parenting",
  "bright-light-therapy",
  "bromazepam-lexotan",
  "buprenorphine-naloxone-suboxone",
  "buprenorphine-subutex",
  "bupropion-wellbutrin",
  "buspirone-buspar",
  "calcium",
  "california-poppy",
  "carbamazepine-tegretol",
  "cariprazine-vraylar",
  "carnitine",
  "cbt-e",
  "chaga-mushroom",
  "chakra-balancing",
  "chamomile",
  "chemogenetics",
  "chicago-parent-program",
  "child-parent-psychotherapy",
  "chiropractic-care",
  "chloral-hydrate",
  "chlordiazepoxide-librium",
  "chlorpromazine-thorazine",
  "chromium",
  "citalopram-celexa",
  "citicoline",
  "clinical-hypnosis",
  "clobazam-onfi",
  "clomipramine-anafranil",
  "clonazepam-klonopin",
  "clonidine-kapvay-catapres",
  "clorazepate-tranxene",
  "closed-loop-neurostimulation",
  "clozapine-clozaril",
  "cognitive-behavioral-therapy",
  "cognitive-behavioral-therapy-insomnia",
  "cognitive-processing-therapy",
  "cognitive-therapy-ptsd",
  "coherence-training",
  "coherent-breathing",
  "collaborative-problem-solving",
  "conscious-discipline",
  "contrave-naltrexone-bupropion",
  "coq10",
  "cordyceps",
  "couples-therapy",
  "craniosacral-therapy",
  "creatine",
  "crispr-mental-health",
  "crystal-healing",
  "curcumin",
  "cyproheptadine-periactin",
  "dance-movement-therapy",
  "dapoxetine-priligy",
  "daridorexant-quviviq",
  "dawn-simulation-therapy",
  "deep-brain-stimulation",
  "deep-tissue-massage",
  "desipramine-norpramin",
  "desvenlafaxine-pristiq",
  "dexmethylphenidate-focalin",
  "dextroamphetamine-amphetamine-adderall",
  "dextroamphetamine-dexedrine",
  "dextromethorphan-bupropion-auvelity",
  "dialectical-behavior-therapy",
  "diazepam-valium",
  "digestive-enzymes",
  "diphenhydramine-benadryl",
  "dir-floortime",
  "disulfiram-antabuse",
  "dmt-therapy",
  "dolphin-assisted-therapy",
  "donepezil-aricept",
  "doxepin-sinequan",
  "doxylamine",
  "drama-therapy",
  "droperidol-inapsine",
  "duloxetine-cymbalta",
  "eeg-neurofeedback",
  "electroacupuncture",
  "electroconvulsive-therapy",
  "emdr",
  "emotion-coaching",
  "emotionally-focused-therapy",
  "epidural-stimulation",
  "equine-assisted-therapy",
  "ericksonian-hypnosis",
  "escitalopram-lexapro",
  "esketamine-spravato",
  "estazolam-prosom",
  "eszopiclone-lunesta",
  "evening-primrose-oil",
  "existential-therapy",
  "experimental-gene-therapy",
  "experimental-glutamate-modulators",
  "explosive-child-approach",
  "exposure-response-prevention",
  "expressive-arts-therapy",
  "families-schools-together",
  "family-based-treatment-fbt",
  "family-preservation-services",
  "family-therapy",
  "fecal-microbiota-transplantation",
  "feldenkrais-method",
  "filial-therapy",
  "fish-oil",
  "flax-seed-oil",
  "fluoxetine-olanzapine-symbyax",
  "fluoxetine-prozac",
  "flupentixol-flaunxol",
  "fluphenazine-prolixin",
  "flurazepam-dalmane",
  "fluvoxamine-luvox",
  "focused-ultrasound",
  "functional-family-therapy",
  "functional-family-therapy-parenting",
  "gaba-supplement",
  "gabapentin-neurontin",
  "galantamine-razadyne-er",
  "gamma-neurofeedback",
  "gentle-parenting",
  "gestalt-therapy",
  "ginkgo-biloba",
  "ginseng",
  "glabellar-botulinum-toxini-injection",
  "glp1",
  "glutamine",
  "glycine",
  "gottman-method",
  "grape-seed-extract",
  "green-tea-extract",
  "group-therapy",
  "guanfacine-intuniv",
  "guided-imagery",
  "habit-reversal-training",
  "haloperidol-haldol",
  "havening-techniques",
  "heart-rate-variability-training",
  "herbal-chinese-medicine",
  "holotropic-breathwork",
  "home-based-family-therapy",
  "homeopathy",
  "hops",
  "horticultural-therapy",
  "hydroxyzine-vistaril-atarax",
  "hypnotherapy",
  "ibogaine-therapy",
  "iloperidone-fanapt",
  "imipramine-tofranil",
  "incredible-years",
  "infrared-light-therapy",
  "intensive-family-services",
  "interpersonal-therapy",
  "iron",
  "isocarboxazid-marplan",
  "iv-ketamine-infusion",
  "jujube",
  "kava",
  "ketamine-assisted-psychotherapy",
  "ketamine-ketalar",
  "ketamine-troche",
  "krill-oil",
  "kundalini-yoga",
  "l-theanine",
  "lactobacillus-helveticus",
  "lactobacillus-rhamnosus",
  "lamotrigine-lamictal",
  "lavender-oral",
  "lemborexant-dayvigo",
  "lemon-balm",
  "levomilnacipran-fetzima",
  "lion-mane-mushroom",
  "lisdexamfetamine-vyvanse",
  "lithium-lithobid",
  "lithium-orotate",
  "lofexidine-lucemyra",
  "logotherapy",
  "lorazepam-ativan",
  "love-and-logic",
  "loving-kindness-meditation",
  "low-field-magnetic-stimulation",
  "loxapine-adasuve",
  "lsd-therapy",
  "lurasidone-latuda",
  "magnesium",
  "magnetic-seizure-therapy",
  "magnolia-bark",
  "mantra-therapy",
  "massage-therapy",
  "mdma-assisted-psychotherapy",
  "meditation",
  "melatonin",
  "memantine-namenda",
  "mentalization-based-therapy",
  "meprobamate-equanil",
  "mescaline-therapy",
  "metformin-psychiatry-weight-gain",
  "methadone",
  "methamphetamine-desoxyn",
  "methohexital-brevital-ect",
  "methotrimeprazine-nozinan",
  "methylphenidate-ritalin-concerta",
  "midazolam-versed-nayzilam",
  "milk-thistle",
  "milnacipran-savella",
  "mindfulness-based-cognitive-therapy",
  "mindfulness-based-stress-reduction",
  "mindfulness-meditation",
  "mirtazapine-remeron",
  "moclobemide-manerix",
  "modafinil-provigil",
  "molindone-moban",
  "multi-strain-probiotics",
  "multidimensional-family-therapy",
  "multidimensional-treatment-foster-care",
  "multimodal-antidepressants",
  "multisystemic-therapy",
  "multisystemic-therapy-families",
  "music-therapy",
  "myofascial-release",
  "n-acetyl-cysteine",
  "nad-precursors",
  "nalmefene-opvee",
  "naloxone-narcan",
  "naltrexone-vivitrol-revia",
  "narrative-exposure-therapy",
  "narrative-therapy",
  "naturopathy",
  "nefazodone-serzone",
  "newborn-behavioral-observations",
  "nicotine-replacement-therapy-nrt",
  "nitrazepam-mogadon",
  "nitrous-oxide-therapy",
  "nmda-antagonists",
  "nortriptyline-pamelor",
  "novel-antidepressants",
  "object-relations-therapy",
  "occupational-therapy",
  "olanzapine-fluoxetine-symbyax",
  "olanzapine-samidorphan-lybalvi",
  "olanzapine-zyprexa",
  "ondansetron-zofran",
  "optogenetics",
  "osteopathic-manipulation",
  "oxazepam-serax",
  "oxcarbazepine-trileptal-oxtellar-xr",
  "oxybate-mixed-salt-xywav",
  "paliperidone-invega",
  "panax-ginseng",
  "parent-child-interaction-therapy",
  "parent-infant-psychotherapy",
  "parent-management-training",
  "paroxetine-paxil",
  "passionflower",
  "periciazine-neuleptil",
  "peripheral-nerve-stimulation",
  "perphenazine-trilafon",
  "person-centered-therapy",
  "phenelzine-nardil",
  "phenobarbital-sezaby",
  "phenylalanine",
  "phosphatidylcholine",
  "phosphatidylserine",
  "phosphorus",
  "photobiomodulation",
  "pimozide-orap",
  "play-therapy-family",
  "poetry-therapy",
  "positive-discipline",
  "potassium",
  "pranayama",
  "prazosin-minipress-ptsd-nightmares",
  "prebiotic-fiber",
  "pregabalin-lyrica",
  "process-groups",
  "prochlorperazine-compazine",
  "progressive-muscle-relaxation",
  "prolonged-exposure-therapy",
  "promethazine-phenergan",
  "propranolol",
  "protriptyline-vivactil",
  "psilocybin-therapy",
  "psychoanalysis",
  "psychoeducational-groups",
  "qigong",
  "quazepam",
  "quercetin",
  "quetiapine-seroquel",
  "ramelteon-rozerem",
  "rasagiline-azilect",
  "rational-emotive-behavior-therapy",
  "real-time-fmri-neurofeedback",
  "reality-therapy",
  "rebirthing-breathwork",
  "recreational-therapy",
  "red-light-therapy",
  "reiki",
  "reishi-mushroom",
  "relationship-development-intervention",
  "remoxipride",
  "restorative-yoga",
  "resveratrol",
  "rhodiola",
  "risperidone-risperdal",
  "rivastigmine-exelon",
  "rolfing",
  "rufinamide-banzel",
  "safinamide-xadago",
  "saw-palmetto",
  "seasonal-affective-disorder-lamp",
  "selegiline-emsam-zelapar",
  "selenium",
  "self-hypnosis",
  "sensory-integration-therapy",
  "sertraline-zoloft",
  "short-term-dynamic-therapy",
  "siberian-ginseng",
  "singing-bowl-therapy",
  "skills-training-groups",
  "skullcap",
  "smr-neurofeedback",
  "sodium-oxybate-xyrem-lumryz",
  "solution-focused-brief-therapy",
  "somatic-experiencing",
  "sound-therapy",
  "spinal-cord-stimulation",
  "spravato-esketamine",
  "st-johns-wort",
  "stiripentol-diacomit",
  "strategic-family-therapy",
  "strengthening-families-program",
  "structural-family-therapy",
  "support-groups",
  "supportive-therapy",
  "suvorexant-belsomra",
  "swedish-massage",
  "tai-chi",
  "tasimelteon-hetlioz",
  "taurine",
  "temazepam-restoril",
  "therapeutic-foster-care",
  "therapeutic-touch",
  "theraplay",
  "thioridazine-mellaril",
  "thiothixene-navane",
  "tiagabine-gabitril",
  "topiramate-topamax",
  "traditional-chinese-medicine",
  "transcendental-meditation",
  "transcranial-direct-current-stimulation",
  "transcranial-focused-ultrasound",
  "transcranial-magnetic-stimulation",
  "transcranial-ultrasound",
  "transference-focused-therapy",
  "transformational-breath",
  "tranylcypromine-parnate",
  "trauma-focused-cbt",
  "trauma-focused-family-therapy",
  "trazodone",
  "trazodone-desyrel",
  "triazolam-halcion",
  "trifluoperazine-stelazine",
  "trigger-point-therapy",
  "trimipramine",
  "triple-p-positive-parenting",
  "triple-reuptake-inhibitors",
  "tryptophan",
  "tummo-meditation",
  "turkey-tail-mushroom",
  "tyrosine",
  "vagus-nerve-stimulation",
  "valerian-root",
  "valproate-depakote",
  "valproate-divalproex",
  "varenicline-chantix",
  "venlafaxine-effexor-xr",
  "vibroacoustic-therapy",
  "video-interaction-guidance",
  "vigabatrin-sabril",
  "vilazodone-viibryd",
  "viloxazine-qelbree",
  "vipassana-meditation",
  "viral-vector-gene-therapy",
  "visualization-therapy",
  "vitamin-b1-thiamine",
  "vitamin-b12-cobalamin",
  "vitamin-b2-riboflavin",
  "vitamin-b3-niacin",
  "vitamin-b5-pantothenic-acid",
  "vitamin-b6-pyridoxine",
  "vitamin-b7-biotin",
  "vitamin-b9-folate",
  "vitamin-c",
  "vitamin-d",
  "vitamin-d3",
  "vitamin-e",
  "vitamin-k",
  "vortioxetine-trintellix",
  "walking-meditation",
  "watch-wait-wonder",
  "wilderness-therapy",
  "wim-hof-method",
  "wraparound-services",
  "xenon-therapy",
  "yin-yoga",
  "yoga-therapy",
  "zaleplon-sonata",
  "zen-meditation",
  "zinc",
  "ziprasidone-geodon",
  "zolpidem-ambien",
  "zonisamide-zonegran-zonisade",
  "zopiclone-imovane",
  "zuclopenthixol-clopixol",
  "zuranolone-zurzuvae",
]);

/**
 * Resolve a requested treatment slug to the canonical slug it should redirect
 * to, or `null` when the slug is already canonical or entirely unknown.
 */
export function resolveTreatmentAlias(slug: string): string | null {
  const target = TREATMENT_SLUG_ALIASES[slug];
  return target && target !== slug ? target : null;
}
